N: 4
#start_synapse: 2
#end_synapse: 3
csv_file_pre: 'spikes_pre_neurons.csv'
csv_file_post: 'spikes_post_neurons.csv'
verbose_summary: False
stdp_rule: 'stdp_pl_synapse_hom_causal'
tau_plus_ms: 20
lambda_pmt: 0.9
alpha: 0.11
mu: 0.4
w_0: 1.

#stdp_rule: 'stdp_pl_synapse_hom'
#tau_plus_ms: 20
#lambda_pmt: 0.9
#alpha: 0.11
#mu: 0.4
#w_0: 1.

#stdp_rule: 'std_stdp'  # or 'spec_stdp
#A_plus: 0.01
#A_minus: 0.012
#tau_plus_ms: 20.0
#tau_minus_ms: 20.0

# Lists for each synapse 1..N
initial_weights:
  - 39.5
  - 39.5
  - 39.5
  - 39.5

axonal_delays_ms:
  - 5.0
  - 5.0
  - 5.0
  - 5.0

dendritic_delays_ms:
  - 0.1
  - 0.1
  - 0.1
  - 0.1