#  config_sim_test_Ax_and_Dendr_Delay_STDP.yaml
#  Copyright © 2025   Pier Stanislao Paolucci   <pier.paolucci@roma1.infn.it>
#  Copyright © 2025   Elena Pastorelli          <elena.pastorelli@roma1.infn.it>
#
#  SPDX-License-Identifier: GPL-3.0-only
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# switch between stdp_pl_synapse_hom_ax_delay and stdp_pl_synapse_hom


described_syn: 3                         # total number of synapses described in this file
add_rand_syn: 0
random_seed: 123456
max_rand_events_per_syn: 5

axonal_support: True

verbose_sim: True
verbose_prediction_summary: False

sim_plot_save: False
prediction_plot_save: False

plot_display: False

# Files storing spikes of pre/post synaptic neurons
csv_file_pre: 'spikes_pre_neurons.csv'
csv_file_post: 'spikes_post_neurons.csv'

# Simulation parameters
T_sim_ms: 200          # Total simulation time (ms)
save_int_ms: 5       # Interval for saving synaptic weights (ms)
# Optional start and end synapse ID to focus sim and analysis on a subset
#start_syn: 0
#end_syn: 5

output_sim_csv: "sim_summary.csv"

# Initial weights for each STDP connection
#W_init: []
W_init: [23.6,67.6,17.9]
W_min: 0. #used when generating additional random events
W_max: 80. #used when generating additional random events

# Synaptic delays for the STDP synapse
#dendritic_delay_ms: []
dendritic_delay_ms: [0.3,0.3,0.1]
min_dendritic_delay_ms: 0.1 #used when generating additional random events
max_dendritic_delay_ms: 0.4 #used when generating additional random events

#axonal_delay_ms: []
axonal_delay_ms: [3.6,3.9,0.7]
min_axonal_delay_ms: 0.0 #used when generating additional random events
max_axonal_delay_ms: 10.0 #used when generating additional random events

# Parameters for both stdp_pl_synapse_hom_ax_delay and stdp_pl_synapse_hom
stdp_params:
  tau_plus: 20.0
  lambda: 0.9
  alpha: 0.11
  mu: 0.4
# w_0 used only by prediction function
w_0: 1.

# A single time-interval list for both pre and post spike trains (in ms)
#spike_train_pre_ms: []
spike_train_pre_ms: [
                    [7.7, 14.6, 42.9, 90.0, 148.5, 170.0],
                    [73.0, 74.8, 170.0],
                    [96.3, 170.0]
                    ]

#spike_train_post_ms: []
spike_train_post_ms: [
                     [145.2, 152.9],
                     [80.9, 102.3, 110.2, 156.6],
                     [92.7, 94.3, 143.7, 144.9]
                     ]

# Large static weights to ensure forced spiking
forced_in_weight:  6000.0  # from spike_generator_in -> pre_neuron
forced_out_weight: 6000.0  # from spike_generator_out -> post_neuron

#plotting params
plot_marker_ms: 50       #time interval of markers in plots

plot_major_ticks_ms: 10

plot_mm: Fals

