#!/usr/bin/env python
# coding: utf-8
#  config.yaml
#  Copyright © 2025   Pier Stanislao Paolucci   <pier.paolucci@roma1.infn.it>
#  Copyright © 2025   Elena Pastorelli          <elena.pastorelli@roma1.infn.it>
#
#  SPDX-License-Identifier: GPL-3.0-only
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# See README.md for documentation

#total number of synaptic events manually specified in this file (can be set to zero)
described_syn: 16  
# total number of synaptic events automatically added using a random generation algorthm (can be set to zero)
add_rand_syn: 1000 

random_seed: 123456
max_rand_events_per_syn: 15

# Simulation vs prediction is always performed
# both AxDsimVSAxDpred and noAxDsimVSnoAxDpred
# Set the following to True if you want also a sim-to-sim comparison
compare_AxDsimVSnoAxDsim: False

# Simulation parameters
T_sim_ms: 200          # Total simulation time (ms)
save_int_ms: 10        # Interval for saving synaptic weights (ms)
resolution: 0.1        # NEST simulator resolution

verbose_sim: False
verbose_pred: False

sim_plot_save: False
prediction_plot_save: False

plot_display: False
plot_mm: False

# Optional start and end synapse ID to focus sim and analysis on a subset
# start_syn: 4
# end_syn: 4

# Initialization for synaptic events manually specified (described_syn)
W_init: [39.5, 39.5, 39.5, 39.5, 39.5, 39.5, 39.5, 39.5, 39.5, 39.5, 39.5, 39.5, 39.5, 39.5, 20.8, 69.0]
dendritic_delay_ms: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 1.0, 1.0, 1.0]
axonal_delay_ms: [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 6.0, 5.5]

# Initialization for synaptic events randomly generated (add_rand_syn)
W_min: 0.
W_max: 80. 
min_dendritic_delay_ms: 0.1 
max_dendritic_delay_ms: 0.4 
min_axonal_delay_ms: 0.0 
max_axonal_delay_ms: 10.0 

# A single time-interval list for both pre and post spike trains (in ms)
spike_train_pre_ms: [
    [50,150],
    [50,150],
    [50,150],
    [50,150],
    [50],
    [50],
    [50],
    [50,150],    
    [10,12,14,100.4],
    [10,12,14,100.4],
    [12,14,100.4],
    [14,100.4],
    [12,100.4],
    [10,100.4],
    [10,100.4],
    [10,100.4],
    ]
                
spike_train_post_ms: [
    [25,60],
    [30,35,60],
    [30,60,70],
    [30,40,60,70],
    [30],
    [30,35],
    [30,35,43],
    [30,35,40,60],
    [19],
    [19,24],
    [19],
    [19],
    [19],
    [10],
    [15],
    [15],
    ]

# Parameters for both stdp_pl_synapse_hom_ax_delay and stdp_pl_synapse_hom
stdp_params:
  tau_plus: 20.0
  lambda: 0.9
  alpha: 0.11
  mu: 0.4
# w_0 used only by prediction function
w_0: 1.

# Neuron parameters
neu_params:
  C_m: 250.0
  E_L: -70.0
  t_ref: 2.0
  tau_m: 10
  V_th: -10.0   # artificially high
  V_reset: -70.0  

# Large static weights to ensure forced spiking
forced_in_weight:  6000.0  # from spike_generator_in -> pre_neuron
forced_out_weight: 6000.0  # from spike_generator_out -> post_neuron





