#!/usr/bin/env python
# coding: utf-8
#  config_sim_test_Ax_and_Dendr_Delay_STDP.yaml
#  Copyright © 2025   Pier Stanislao Paolucci   <pier.paolucci@roma1.infn.it>
#  Copyright © 2025   Elena Pastorelli          <elena.pastorelli@roma1.infn.it>
#
#  SPDX-License-Identifier: GPL-3.0-only
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

# switch between stdp_pl_synapse_hom_ax_delay and stdp_pl_synapse_hom

described_syn: 0                          # total number of synapses described in this file
add_rand_syn: 1000
random_seed: 123456
max_rand_events_per_syn: 15

verbose_sim: False
verbose_pred: False

sim_plot_save: False
prediction_plot_save: False

plot_display: False

# Create a folder with timestamp and copy there output files
save_files_in_folder: False      

# Files storing spikes of pre/post synaptic neurons
csv_file_pre: 'spikes_pre_neurons.csv'
csv_file_post: 'spikes_post_neurons.csv'

# Simulation parameters
T_sim_ms: 200          # Total simulation time (ms)
save_int_ms: 10        # Interval for saving synaptic weights (ms)
resolution: 0.1        # NEST simulator resolution
# Optional start and end synapse ID to focus sim and analysis on a subset
#start_syn: 4
#end_syn: 4

# Initial weights for each STDP connection
W_init: []
W_min: 0. #used when generating additional random events
W_max: 80. #used when generating additional random events

# Synaptic delays for the STDP synapse
dendritic_delay_ms: []
min_dendritic_delay_ms: 0.1 #used when generating additional random events
max_dendritic_delay_ms: 0.4 #used when generating additional random events

axonal_delay_ms: []
min_axonal_delay_ms: 0.0 #used when generating additional random events
max_axonal_delay_ms: 10.0 #used when generating additional random events

# A single time-interval list for both pre and post spike trains (in ms)
spike_train_pre_ms: []
spike_train_post_ms: []

# Parameters for both stdp_pl_synapse_hom_ax_delay and stdp_pl_synapse_hom
stdp_params:
  tau_plus: 20.0
  lambda: 0.9
  alpha: 0.11
  mu: 0.4
# w_0 used only by prediction function
w_0: 1.

# Neuron parameters
neu_params:
  C_m: 250.0
  E_L: -70.0
  t_ref: 2.0
  tau_m: 10
  V_th: -10.0   # artificially high
  V_reset: -70.0  

# Large static weights to ensure forced spiking
forced_in_weight:  6000.0  # from spike_generator_in -> pre_neuron
forced_out_weight: 6000.0  # from spike_generator_out -> post_neuron

plot_mm: False

compare_AxDsimVSnoAxDsim: False

