# Simulation parameters
T_sim_ms: 600          # Total simulation time (ms)
save_int_ms: 10        # Interval for saving synaptic weights (ms)
N: 5                    # Number of synapses


# A single time-interval list for both pre and post spike trains (in ms)
train_dt_pre_ms: [200.0, 200.0, 200.0, 200.0, 200.0] 
train_dt_post_ms: [200.0, 200.0, 200.0, 200.0, 200.0] 
offset_dt_post_ms: [-0.5, -0.5, -0.5, -0.5, -0.5] 

# Synaptic delays for the STDP synapse
delay: [1.0, 1.0, 1.0, 1.0, 1.0]
axonal_delay: [.0, .0, .0, .0, .0]

# Synaptic model
axonal_support: False

# Initial weights for each STDP connection
W0: [1., 38., 39.5, 41., 50.]

# Parameters for stdp_pl_synapse_hom 
# (see NEST docs for available parameters: e.g., A_plus, A_minus, tau_plus, tau_minus, ...)
stdp_params:
  tau_plus: 20.0
  lambda: 0.9
  alpha: 0.11
  mu: 0.4
  # Some models also support learning rate or homeostatic params 
  # (like 'alpha', 'eta', etc.). Adjust if needed.

# Large static weights to ensure forced spiking
forced_in_weight:  6000.0  # from spike_generator_in -> pre_neuron
forced_out_weight: 6000.0  # from spike_generator_out -> post_neuron

#plotting params
plot_tick_ms: 100       #time interval of ticks in plots    
